import Link from 'next/link';
import {Download,BookOpen,GraduationCap} from 'lucide-react';
import {Empty,FilterBar,PageHead,Pager,Pill,TenantSelect} from '@/components/ui';
import {adminClient,requireDeveloper,validateUUID} from '@/lib/supabase';
import {allTenants} from '@/lib/queries';
import {date,datetime,shortId} from '@/lib/format';
import {entityKinds,kindLabels,type LearningEntity} from '@/lib/types';
function summary(e:LearningEntity){const d=e.data;return String(d.name||d.title||d.date||d.unitKey||d.status||d.answer||e.kind).slice(0,100)}
export default async function Academics({searchParams}:{searchParams:Promise<{tenant?:string;kind?:string;page?:string}>}){
 await requireDeveloper();const sp=await searchParams;const tenant=validateUUID(sp.tenant||'')?sp.tenant:'';const kind=(entityKinds as readonly string[]).includes(sp.kind||'')?sp.kind:'';
 const page=Math.max(1,Math.min(10000,Number(sp.page)||1));const size=20;const db=adminClient();const tenants=await allTenants();const names=Object.fromEntries(tenants.map(t=>[t.id,t.name]));
 let query=db.from('learning_entities').select('id,tenant_id,kind,data,author_id,created_at',{count:'exact'}).order('created_at',{ascending:false}).range((page-1)*size,page*size-1);
 if(tenant)query=query.eq('tenant_id',tenant);if(kind)query=query.eq('kind',kind);
 const [{data,error,count},byKind]=await Promise.all([query,Promise.all(entityKinds.map(async k=>{let q=db.from('learning_entities').select('*',{count:'exact',head:true}).eq('kind',k);if(tenant)q=q.eq('tenant_id',tenant);const r=await q;if(r.error)throw new Error(r.error.message);return {kind:k,count:r.count||0}}))]);
 if(error)throw new Error(error.message);const records=(data||[]) as LearningEntity[];
 return <><PageHead overline="ACADEMIC MONITORING" title="Aktivitas akademik" description="Pantau kelas, materi, jadwal, tugas, hafalan, dan presensi dari seluruh instansi, tanpa mengubah data operasional."/><div className="export-bar"><Link className="button secondary small" href={"/api/export/akademik?"+new URLSearchParams({...(tenant?{tenant}:{}),...(kind?{kind}:{})}).toString()}><Download size={16}/> Ekspor CSV</Link></div><section className="kind-cards">{byKind.map(x=><a key={x.kind} href={'/akademik?'+new URLSearchParams({...(tenant?{tenant}:{}),kind:x.kind}).toString()} className={'kind-card '+(x.kind===kind?'selected':'')}><BookOpen size={19}/><strong>{x.count.toLocaleString('id-ID')}</strong><span>{kindLabels[x.kind]}</span></a>)}</section><section className="surface"><div className="surface-heading"><div><h2>Riwayat data pembelajaran</h2><p>Tampilan pemantauan lintas instansi.</p></div><span className="surface-count"><GraduationCap size={16}/>{count||0} catatan</span></div><div className="surface-pad"><FilterBar action="/akademik" hideSearch ><TenantSelect value={tenant} tenants={tenants}/><select name="kind" defaultValue={kind}><option value="">Semua jenis</option>{entityKinds.map(k=><option value={k} key={k}>{kindLabels[k]}</option>)}</select></FilterBar></div><div className="table-scroll"><table className="data-table"><thead><tr><th>AKTIVITAS</th><th>JENIS</th><th>INSTANSI</th><th>DIBUAT</th><th>ID</th></tr></thead><tbody>{records.map(e=><tr key={e.id}><td className="academic-summary"><b>{summary(e)}</b><span className="subline">{e.kind==='memorization'?'Rekaman setoran':e.kind==='attendance'?'Data presensi':'Data pembelajaran'}</span></td><td><span className="simple-tag">{kindLabels[e.kind]||e.kind}</span></td><td className="cell-muted">{names[e.tenant_id]||'—'}</td><td className="cell-muted">{datetime(e.created_at)}</td><td className="cell-muted mono">{shortId(e.id)}</td></tr>)}</tbody></table>{!records.length&&<Empty text="Belum ada aktivitas untuk filter ini."/>}</div><Pager base="/akademik" page={page} count={count||0} pageSize={size} filters={{tenant,kind}}/></section><div className="info-box"><b>Hak akses akademik</b><p>Fungsi <code>save_learning_entity</code> pada SQL secara eksplisit menolak role developer. Panel ini memakai pembacaan server yang sudah diautentikasi dan tidak menyediakan bypass untuk mengubah/menghapus riwayat kelas atau siswa.</p></div></>;
}
