'use client';
import {useActionState,useEffect,useState,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {Eye,EyeOff,Plus,X,AlertCircle,CheckCircle2} from 'lucide-react';
import {loginAction,saveTenantAction,saveManagerAction,toggleTenantAction,savePricingAction,saveProfileAction,savePasswordAction} from '@/app/actions';
import {initialAction,type ActionResult,type Tenant,type Profile} from '@/lib/types';
import {toLocalDate} from '@/lib/format';

function Feedback({state}:{state:ActionResult}){return state.message?<div role="status" className={'form-alert '+(state.ok?'ok':'error')}>{state.ok?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>}<span>{state.message}</span></div>:null;}
export function LoginForm(){
 const [state,action,pending]=useActionState(loginAction,initialAction);const [show,setShow]=useState(false);
 return <form action={action} className="login-form"><label>Email Developer<input name="email" type="email" autoComplete="email" placeholder="developer@platform.id" required/></label><label>Kata sandi<div className="password-wrap"><input name="password" type={show?'text':'password'} autoComplete="current-password" placeholder="Masukkan kata sandi" required/><button type="button" aria-label={show?'Sembunyikan password':'Tampilkan password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><Feedback state={state}/><button className="button primary full-width login-submit" type="submit" disabled={pending}>{pending?'Memverifikasi…':'Masuk ke Dashboard →'}</button></form>;
}
export function Modal({title,sub,onClose,children}:{title:string,sub?:string,onClose:()=>void,children:React.ReactNode}){
 return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-label={title} className="modal"><header className="modal-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div><button className="icon-btn" type="button" onClick={onClose} aria-label="Tutup"><X size={21}/></button></header>{children}</section></div>;
}
function useAfterSuccess(state:ActionResult,onClose?:()=>void){const router=useRouter();const closeRef=useRef(onClose);closeRef.current=onClose;useEffect(()=>{if(state.ok){router.refresh();closeRef.current?.()}},[state.ok,router]);}
export function TenantControls(){
 const [edit,setEdit]=useState<Tenant|null|undefined>(undefined);
 return <><button className="button primary" onClick={()=>setEdit(null)}><Plus size={18}/> Tambah instansi</button>{edit!==undefined&&<Modal title={edit?'Ubah instansi':'Tambah instansi'} sub="Pengaturan ini berlaku langsung untuk aplikasi Flutter." onClose={()=>setEdit(undefined)}><TenantFields key={edit?.id||'create'} tenant={edit} onClose={()=>setEdit(undefined)}/></Modal>}</>;
}
export function TenantEditButton({tenant}:{tenant:Tenant}){
 const [open,setOpen]=useState(false);
 return <><button className="button small secondary" onClick={()=>setOpen(true)}>Ubah</button>{open&&<Modal title={'Ubah '+tenant.name} sub="Perubahan langsung diterapkan ke instansi." onClose={()=>setOpen(false)}><TenantFields tenant={tenant} onClose={()=>setOpen(false)}/></Modal>}</>;
}
function TenantFields({tenant,onClose}:{tenant?:Tenant|null,onClose:()=>void}){
 const [state,action,pending]=useActionState(saveTenantAction,initialAction);useAfterSuccess(state,onClose);
 return <form action={action} className="modal-body form-grid"><input type="hidden" name="id" value={tenant?.id||''}/><label className="field wide">Nama instansi<input name="name" defaultValue={tenant?.name||''} required maxLength={160} placeholder="Contoh: Pondok Al-Hikmah"/></label><label className="field">Kode instansi<input name="code" defaultValue={tenant?.code||''} required maxLength={24} pattern="[A-Za-z0-9_-]{3,24}" placeholder="ALHIKMAH" style={{textTransform:'uppercase'}}/></label><label className="field">Paket<select name="plan" defaultValue={tenant?.plan||'Dasar'}><option>Dasar</option><option>Sekolah</option><option>Pesantren</option></select></label><label className="field">Status<select name="status" defaultValue={tenant?.status||'active'}><option value="active">Aktif</option><option value="suspended">Ditangguhkan</option></select></label><label className="field">Masa aktif sampai<input type="date" name="expires" defaultValue={tenant?toLocalDate(tenant.expires_at):toLocalDate(new Date(Date.now()+366*86400000).toISOString())} required/></label><label className="field">Tahun akademik<input name="academic_year" defaultValue={tenant?.academic_year||'2026/2027'} required/></label><label className="field">Semester<select name="semester" defaultValue={tenant?.semester||'Ganjil'}><option>Ganjil</option><option>Genap</option></select></label><label className="field wide">Alamat<input name="address" defaultValue={tenant?.address||''}/></label><label className="field">Kontak<input name="contact" defaultValue={tenant?.contact||''}/></label><label className="field">Target hafalan<input type="number" name="target_count" min="1" max="1000" defaultValue={tenant?.target_count||20}/></label><div className="wide"><Feedback state={state}/></div><div className="modal-footer wide"><button type="button" className="button secondary" onClick={onClose}>Batal</button><button type="submit" className="button primary" disabled={pending}>{pending?'Menyimpan…':'Simpan instansi'}</button></div></form>;
}
export function TenantStatusButton({tenant}:{tenant:Tenant}){
 const [state,action,pending]=useActionState(toggleTenantAction,initialAction);
 const [confirm,setConfirm]=useState(false);useAfterSuccess(state,()=>setConfirm(false));
 return <><button className={'button small '+(tenant.status==='active'?'outline-danger':'outline-success')} onClick={()=>setConfirm(true)} type="button">{tenant.status==='active'?'Tangguhkan':'Aktifkan'}</button>{confirm&&<Modal title={tenant.status==='active'?'Tangguhkan instansi?':'Aktifkan instansi?'} sub={tenant.status==='active'?'Semua akun instansi akan kehilangan akses hingga diaktifkan kembali.':'Akses tetap bergantung pada tanggal masa aktif.'} onClose={()=>setConfirm(false)}><form action={action} className="modal-body"><input type="hidden" name="id" value={tenant.id}/><p><b>{tenant.name}</b> — {tenant.code}</p><Feedback state={state}/><div className="modal-footer"><button type="button" className="button secondary" onClick={()=>setConfirm(false)}>Batal</button><button type="submit" className="button primary" disabled={pending}>{pending?'Memproses…':'Ya, lanjutkan'}</button></div></form></Modal>}</>;
}
export function ManagerCreateButton({tenants}:{tenants:Tenant[]}){
 const [open,setOpen]=useState(false);return <><button className="button primary" onClick={()=>setOpen(true)}><Plus size={18}/> Tambah pengelola</button>{open&&<Modal title="Buat akun pengelola" sub="Hanya Admin dan Pimpinan instansi yang dapat dibuat Developer." onClose={()=>setOpen(false)}><ManagerFields tenants={tenants} onClose={()=>setOpen(false)}/></Modal>}</>;
}
export function ManagerEditButton({manager,tenants}:{manager:Profile,tenants:Tenant[]}){
 const [open,setOpen]=useState(false);return <><button className="button small secondary" onClick={()=>setOpen(true)}>Ubah</button>{open&&<Modal title="Ubah akun pengelola" sub="Email, role, dan instansi tidak bisa diganti setelah dibuat." onClose={()=>setOpen(false)}><ManagerFields manager={manager} tenants={tenants} onClose={()=>setOpen(false)}/></Modal>}</>;
}
function ManagerFields({manager,tenants,onClose}:{manager?:Profile,tenants:Tenant[],onClose:()=>void}){
 const [state,action,pending]=useActionState(saveManagerAction,initialAction);useAfterSuccess(state,onClose);
 return <form action={action} className="modal-body form-grid"><input type="hidden" name="id" value={manager?.id||''}/><label className="field wide">Nama lengkap<input name="name" required maxLength={160} defaultValue={manager?.name||''}/></label><label className="field wide">Email<input type="email" name="email" required readOnly={!!manager} defaultValue={manager?.email||''}/></label><label className="field">Role<select name="role" disabled={!!manager} defaultValue={manager?.role||'leader'}><option value="leader">Pimpinan</option><option value="admin">Admin</option></select>{manager&&<input type="hidden" name="role" value={manager.role}/>}</label><label className="field">Instansi<select name="tenant_id" disabled={!!manager} required defaultValue={manager?.tenant_id||''}><option value="" disabled>Pilih instansi</option>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>{manager&&<input type="hidden" name="tenant_id" value={manager.tenant_id||''}/>}</label><label className="field">Nomor HP<input name="phone" maxLength={40} defaultValue={manager?.phone||''}/></label><label className="field">Status<select name="active" defaultValue={manager?.active===false?'false':'true'}><option value="true">Aktif</option><option value="false">Nonaktif</option></select></label>{!manager&&<label className="field wide">Password awal (minimal 12 karakter)<input name="password" required type="password" autoComplete="new-password" minLength={12} maxLength={72}/><span className="helper">Buat password kuat, lalu sampaikan kepada pengelola melalui saluran aman.</span></label>}<div className="wide"><Feedback state={state}/></div><div className="modal-footer wide"><button type="button" className="button secondary" onClick={onClose}>Batal</button><button className="button primary" disabled={pending} type="submit">{pending?'Menyimpan…':manager?'Simpan perubahan':'Buat akun'}</button></div></form>;
}
export function PriceForm({monthly,annual}:{monthly:number,annual:number}){
 const [state,action,pending]=useActionState(savePricingAction,initialAction);useAfterSuccess(state);
 return <form action={action} className="settings-form"><div className="form-grid"><label className="field">Harga bulanan (Rp)<input type="number" name="monthly" min="1000" max="100000000" step="1" required defaultValue={monthly}/></label><label className="field">Harga tahunan (Rp)<input type="number" name="annual" min="1000" max="100000000" step="1" required defaultValue={annual}/></label></div><p className="helper">Perubahan harga berlaku untuk transaksi baru; pembayaran lama tidak diubah.</p><Feedback state={state}/><button type="submit" className="button primary" disabled={pending}>{pending?'Menyimpan…':'Simpan harga langganan'}</button></form>;
}
export function ProfileForm({profile}:{profile:Profile}){
 const [state,action,pending]=useActionState(saveProfileAction,initialAction);useAfterSuccess(state);
 return <form action={action} className="settings-form"><label className="field">Nama lengkap<input name="name" required defaultValue={profile.name}/></label><label className="field">Email developer<input value={profile.email} readOnly disabled/></label><label className="field">Nomor HP<input name="phone" defaultValue={profile.phone}/></label><Feedback state={state}/><button type="submit" className="button primary" disabled={pending}>{pending?'Menyimpan…':'Simpan profil'}</button></form>;
}
export function PasswordForm(){
 const [state,action,pending]=useActionState(savePasswordAction,initialAction);
 return <form action={action} className="settings-form"><label className="field">Password baru<input name="password" minLength={12} type="password" autoComplete="new-password" required/></label><label className="field">Konfirmasi password<input name="confirm" type="password" autoComplete="new-password" required/></label><Feedback state={state}/><button type="submit" className="button secondary" disabled={pending}>{pending?'Mengubah…':'Ubah password'}</button></form>;
}
